# Generated by GPT-5 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Ключевое слово",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключевое слово",
                "verbose_name_plural": "Ключевые слова",
                "ordering": ["word"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                to="services.keyword",
                verbose_name="Ключевые слова",
            ),
        ),
    ]

