# Generated by Django 5.2.13 on 2026-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыта'),
        ),
    ]
