# Generated by GPT-5 on 2026-05-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_keyword_and_service_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="keywords",
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
    ]

