# Generated by Django 5.2.13 on 2026-04-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='Имя инициатора')),
                ('actor_role', models.CharField(blank=True, max_length=20, verbose_name='Роль инициатора')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('impersonate', 'Вход за пользователя'), ('stop_impersonate', 'Возврат из impersonation')], max_length=32, verbose_name='Действие')),
                ('entity_type', models.CharField(blank=True, max_length=64, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сущности')),
                ('entity_repr', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='admin_panel_entity__4fbcc7_idx'), models.Index(fields=['action'], name='admin_panel_action_d5e0a0_idx'), models.Index(fields=['actor'], name='admin_panel_actor_i_1de362_idx')],
            },
        ),
    ]
