"""
Django settings for reflection project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-1nzv4*^ksy3&-l8qy6fu=o!t-+760jwv@hxo$b)&hv)5v1ohbm",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv("DJANGO_DEBUG") or "1").lower() in ("1", "true", "yes", "y", "on")

def _split_hosts(raw: str) -> list[str]:
    return [h.strip() for h in (raw or "").split(",") if h.strip()]


_env_hosts = _split_hosts(os.getenv("DJANGO_ALLOWED_HOSTS") or "")
_default_hosts = ["localhost", "127.0.0.1", "[::1]"]
# Если DJANGO_ALLOWED_HOSTS задан (прод-домен и т.п.), всё равно добавляем локальные хосты —
# иначе Docker/Nginx на https://localhost даёт DisallowedHost при локальной проверке.
ALLOWED_HOSTS = sorted(set(_env_hosts + _default_hosts)) if _env_hosts else list(_default_hosts)

_csrf_raw = (os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS") or "").strip()
_csrf_env = [x.strip() for x in _csrf_raw.split(",") if x.strip()]
_csrf_defaults = [
    "http://localhost",
    "http://127.0.0.1",
    "https://localhost",
    "https://127.0.0.1",
]
CSRF_TRUSTED_ORIGINS = sorted(set(_csrf_env + _csrf_defaults)) if _csrf_env else list(_csrf_defaults)

if (os.getenv("DJANGO_BEHIND_HTTPS_PROXY") or "").lower() in ("1", "true", "yes", "y", "on"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main.apps.ServicesConfig",
    "admin_panel.apps.AdminPanelConfig",
    "services",
    "reviews",
    "booking",
    "users",
]

AUTH_USER_MODEL = "users.User"

# Куда редиректить неавторизованных пользователей.
# Используется login_required, redirect_to_login и нашими декораторами ролей.
LOGIN_URL = "users:login"

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# Путь к папке статики в корне проекта
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Папка, куда соберется вся статика при команде collectstatic (для сервера)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (Загружаемые пользователем файлы: аватарки, фото услуг)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Логирует переходы пользователей по страницам в системный лог.
    # Должен идти после AuthenticationMiddleware, чтобы был доступен request.user.
    "main.middleware.NavigationLoggingMiddleware",
    # Прокидывает request.user / IP / User-Agent в thread-local, чтобы
    # сигналы аудита могли атрибутировать действия конкретному админу.
    "admin_panel.middleware.AuditContextMiddleware",
    # Логирует выполненные SQL-запросы в in-memory буфер для страницы БД
    # в админке. Активен только на запросах авторизованного админа.
    "admin_panel.middleware.QueryLogMiddleware",
]

ROOT_URLCONF = "reflection.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "main" / "templates",  # здесь base.html
            BASE_DIR / "services" / "templates",
            BASE_DIR / "reviews" / "templates",
            BASE_DIR / "booking" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "booking.context_processors.booking_form_context",
                "admin_panel.context_processors.impersonation",
                "main.context_processors.moderator_preview",
                "main.context_processors.preview_mode",
            ],
        },
    },
]

WSGI_APPLICATION = "reflection.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("DJANGO_SQLITE_PATH") or (BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# LOGGING
# Логи складываются в media/logs/YYYY-MM/DD.log — по одной папке на месяц,
# по одному файлу на день. Это даёт:
#   * лёгкий архив по датам;
#   * простую выгрузку истории в админке;
#   * отсутствие огромных файлов.
# ---------------------------------------------------------------------------
APP_LOG_DIR = MEDIA_ROOT / "logs"
APP_LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "app": {
            "format": "{asctime} | {levelname:<7} | {name:<18} | {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "app",
        },
        "app_file": {
            "()": "main.log_handler.DailyFolderFileHandler",
            "base_dir": str(APP_LOG_DIR),
            "formatter": "app",
        },
    },
    "loggers": {
        "app": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",  # чтобы не тонуть в служебных сообщениях
            "propagate": False,
        },
        # Access-log dev-сервера дублирует то, что пишет наш NavigationLoggingMiddleware.
        # Поэтому в файл его не гоним — только в консоль для разработчика.
        "django.server": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # 403/404 уже красиво логируются через app.nav с пользователем и страницей,
        # поэтому дублирующие "Forbidden:/Not Found:" от django.request не нужны —
        # оставляем только реальные ошибки (5xx).
        "django.request": {
            "handlers": ["console", "app_file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
